### ISSUE TITLE
OOBE broken in steam.target

### ISSUE THREAD

**Issue by samueldr** [Jovian-Experiments/Jovian-NixOS#10]
This is a known issue with the "PAL" beta, and happens on other non-steamos distros.

### Workaround

Log-in to your steam account using the desktop steam interface.

**Comment by samueldr** [comment]
Unsourced clues: look at strace during oobe, and see if it's trying to execute any of these, then "snitch" on the params with a "snitcher" script added to the FHS to see what we can do to make it happy:

 - /usr/bin/steamos-update
 - /usr/bin/steamos-session-select

**Comment by zhaofengli** [comment]
I [managed](https://github.com/zhaofengli/Jovian-NixOS/commit/7c364a1362a5f31a0471f79eb9a9e247221b2594) to get past the OS update step in the OOBE wizard, where the wizard would attempt to execute `sudo -n steamos-update` and fail. `steamos-update` itself is a shell script that can be found in the [`jupiter-legacy-support`](https://steamdeck-packages.steamos.cloud/archlinux-mirror/jupiter/os/x86_64/jupiter-legacy-support-1.116-1-any.pkg.tar.zst) package in SteamOS. If no updates are found, it exits with code 7.

The other half of the problem is [`sudo` not working in FHS environments](https://github.com/NixOS/nixpkgs/issues/42117). For now I'm working around it with a dummy `sudo` script that doesn't actually escalate privileges.

**Comment by samueldr** [comment]
Has anyone tested the OOBE login flow since then?

@lheckemann, you're setting up a new Steam Deck, did you go through the OOBE wizard? (Setting up your Steam account using the Steam Deck interface.)

**Comment by lheckemann** [comment]
I did, and it kind of worked? It got a bit confused by networks already being set up, but I was able to log in just fine like on SteamOS.

Also, for keeping track of execs, I can very much recommend `execsnoop` from linuxPackages.bcc -- it has a lot less overhead than strace, and there are loads more useful tools in bcc as well.

**Comment by samueldr** [comment]
Closing, then. I think this was indeed meant to be solved by the recent work @zhaofengli put in.
