### ISSUE TITLE
Investigate CPU governor

### ISSUE THREAD

**Issue by samueldr** [Jovian-Experiments/Jovian-NixOS#15]
It is known (via single thread benchmarking with 7z) that the `powersave` governor can leave compute power on the table.

Investigate whether it would be a better default to change it to `ondemand` or `performance`, especially with gaming scnearios in mind.

Also: what does upstream SteamOS do?

Hints:

`powerManagement.cpuFreqGovernor = "performance";`

`sudo cpupower frequency-set -g ondemand`

```
 $ grep . /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor:powersave
/sys/devices/system/cpu/cpu1/cpufreq/scaling_governor:powersave
/sys/devices/system/cpu/cpu2/cpufreq/scaling_governor:powersave
/sys/devices/system/cpu/cpu3/cpufreq/scaling_governor:powersave
/sys/devices/system/cpu/cpu4/cpufreq/scaling_governor:powersave
/sys/devices/system/cpu/cpu5/cpufreq/scaling_governor:powersave
/sys/devices/system/cpu/cpu6/cpufreq/scaling_governor:powersave
/sys/devices/system/cpu/cpu7/cpufreq/scaling_governor:powersave
```

**Comment by rapenne-s** [comment]
I found schedutil to be the most performant in term of framerate, both on SteamOS and openSUSE, however, setting to performance was giving a few less FPS but was drawing ~0.5 watts less

going down the rabbit hole, I tried to use amd-pstate but it's not unfortunately not compatible with the deck CPU because of a missing extension :/

**Comment by samueldr** [comment]
(Closing, nothing to really do... and some scheduler change is upcoming anyway, meaning this old issue is becoming irrelevant)
