### ISSUE TITLE
is there a way to use destop for compiling

### ISSUE THREAD

**Issue by xiro-codes** [Jovian-Experiments/Jovian-NixOS#176]
building the kernel takes forever how can i off load this to my desktop ?

**Comment by nat522** [comment]
I don’t believe so

**Comment by samueldr** [comment]
Yes there is. There are a couple ways to achieve this. I won't go into details since I don't have the time, but here's some resources to start looking into it:

Using Nix distributed builds

 - In the Nix manual: https://nixos.org/manual/nix/stable/advanced-topics/distributed-builds.html
 - On the Wiki (user-contributed notes): https://nixos.wiki/wiki/Distributed_build

Or using `nixos-rebuild --build-host`

(From man nixos-rebuild)

```
--build-host host
        Instead of building the new configuration locally, use the specified host to perform the
        build. The host needs to be accessible with ssh, and must be able to perform Nix builds.
        If  the  option --target-host is not set, the build will be copied back to the local ma‐
        chine when done.

        Note that, if --no-build-nix is not specified, Nix will be built both  locally  and  re‐
        motely.  This  is because the configuration will always be evaluated locally even though
        the building might be performed remotely.

        You can include a remote user name in the host name (user@host). You can  also  set  ssh
        options by defining the NIX_SSHOPTS environment variable.
```
