### ISSUE TITLE
Gamescope uses the default x11 cursor theme instead of the steam os one

### ISSUE THREAD

**Issue by toast003** [Jovian-Experiments/Jovian-NixOS#208]
I'm guessing that it's like this cause the package that has the steam os cursor theme isn't installed by default

**Comment by pongo1231** [comment]
The default cursor theme path inside gamescope-session is already substituted with the one of steamdeck-hw-theme [here](https://github.com/Jovian-Experiments/Jovian-NixOS/blob/964c5c36033fb4761cd6676c76bee6fadf06a75d/pkgs/gamescope-session/default.nix#L110). ~~Perhaps `usr/share/icons/steam/` from jupiter-hw-support has to also be available inside the FHS environment?~~  gamescope-session doesn't run inside an FHS env, only steam IIRC so that won't work.

**Comment by toast003** [comment]
Just took a look at the gamescope-session on the PKGBUILDs repo and I found that XCURSOR_THEME is being set [here](https://github.com/Jovian-Experiments/PKGBUILDs-mirror/blob/35a75b6e09225e124558a9ffb6b0b22958349fb8/gamescope-session#L157)
Apparently that overrides it?

**Comment by toast003** [comment]
According to https://wiki.archlinux.org/title/Cursor_themes#Environment_variable it does
Thankfully XCURSOR_PATH also exists, so we could just set that to the path of steamdeck-hw-theme?

**Comment by K900** [comment]
https://github.com/Jovian-Experiments/Jovian-NixOS/pull/211 seems to work for me.

**Comment by toast003** [comment]
Works for me too, although I'm confused on why you also added breeze to the xcursor path

**Comment by K900** [comment]
The Steam theme inherits from Breeze_Snow.
