### ISSUE TITLE
cdg.desktopSession only works for plasma

### ISSUE THREAD

**Issue by minego** [Jovian-Experiments/Jovian-NixOS#275]
The cfg.desktopSession option doesn't seem to work for me. I was digging through to try to understand what I might be doing wrong, but I don't see how it could ever work for anything except plasma...

Here it sets an environment variable to the specified value

https://github.com/Jovian-Experiments/Jovian-NixOS/blob/e2c026d8efea340d2a2dcc56775212979dd51ef2/modules/steam/autostart.nix#L89

Then that variable appears to be used here:

https://github.com/Jovian-Experiments/Jovian-NixOS/blob/e2c026d8efea340d2a2dcc56775212979dd51ef2/pkgs/steam-jupiter/fhsenv.nix#L31

But, that script compares it to "plasma" and exits if it doesn't match. But, I don't want it to match because I want to use something else! 😄 

Am I reading that right?

**Comment by samueldr** [comment]
The `desktopSession` option works. What might not is whatever session you've selected.

* * *

It is not doing what you might think from a quick glance. The script compares with plasma since *Steam* will call it with `plasma` as an argument to switch to the desktop session.

 - [The `steamos-session-select` script is called by Steam with `plasma` as the argument when selecting a desktop session](https://github.com/Jovian-Experiments/Jovian-NixOS/blob/e2c026d8efea340d2a2dcc56775212979dd51ef2/pkgs/steam-jupiter/fhsenv.nix#L27-L35)
 - [Which we allow the user to override in their config via `JOVIAN_DESKTOP_SESSION`](https://github.com/Jovian-Experiments/Jovian-NixOS/blob/e2c026d8efea340d2a2dcc56775212979dd51ef2/pkgs/steam-jupiter/fhsenv.nix#L37-L40)
 - [Our greetd greeter load the `.local/state/steamos-session-select` file](https://github.com/Jovian-Experiments/Jovian-NixOS/blob/e2c026d8efea340d2a2dcc56775212979dd51ef2/pkgs/jovian-greeter/greeter.py#L149) as the session to run

Also, worthy of note, this is "undone" by the greeter on session switching, such that logging out goes back to steam. It's why it's "correct" that we only check for `plasma` there.

 - https://github.com/Jovian-Experiments/Jovian-NixOS/blob/e2c026d8efea340d2a2dcc56775212979dd51ef2/pkgs/jovian-greeter/greeter.py#L132
 - https://github.com/Jovian-Experiments/Jovian-NixOS/blob/e2c026d8efea340d2a2dcc56775212979dd51ef2/pkgs/jovian-greeter/consume-session#L25

 Really, we could also drop the check entirely... technically... There are no closed-source component involved in switching back to the Steam session. So the `steamos-session-select` script could "just" write the flag, and the risk would be that if this gets used for another feature by Valve and Steam down the line, it'd still drop the user desktop session... instead of breaking in a weird manner... :thinking:

**Comment by minego** [comment]
Okay, reading closer I see I may be wrong.

Is the script always called with "plasma" as the original arg and then the environment variable is used later?

**Comment by samueldr** [comment]
Exactly

**Comment by minego** [comment]
Ah, yeah you replied just as I was writing that :-)

That information helps a lot, thank you. I'll debug my setup more tomorrow. Thank you.

**Comment by minego** [comment]
I finally figured out why mine wasn't working, and was able to correct it. I posted on the discussion thread about this as well in hopes that it may help anyone else who runs into a similar issue.

Originally I was specifying my session:
```
services.xserver.displayManager.session = [{
			manage									= "desktop";
			name									= "dwl";
			start = ''
                ${pkgs.dwl}/bin/dwl &
                waitPID=$!
                '';
		}];
```

This works on my desktop systems using greetd with regreet, but does NOT work with Jovian's greeter. So, I spent some time digging through source and trying to understand it. So, I looked at a compositor that we know does work:

https://github.com/Jovian-Experiments/Jovian-NixOS/blob/e2c026d8efea340d2a2dcc56775212979dd51ef2/pkgs/gamescope-session/default.nix#L151

That line was something I had not seen before. So, I updated my dwl package to provide that:
```
passthru.providedSessions = [ "dwl" ];
```
This syntax assumes that the package provides a session .desktop file, and my package does. If yours doesn't then you'll also need to update it to create that file in `$out/share/wayland-sessions/$name.desktop`

Then in my configuration I replaced the section above with:
```
		services.xserver.displayManager.sessionPackages = [
			pkgs.dwl-unwrapped
		];
```

So, with that it is all working! Thanks for the help and explanation of the way the script works above. That was really helpful.
