### ISSUE TITLE
Verify and fix iso image boot from USB

### ISSUE THREAD

**Issue by samueldr** [Jovian-Experiments/Jovian-NixOS#39]
There are now multiple reports of iso image not booting from USB.

From a while back, @ElvishJerricco wasn't able to boot the NixOS iso from USB.

Now in the matrix room, a new user also isn't able from USB.

**Comment by samueldr** [comment]
> [03:42] 321, jiayou!
>
> oh ×××, I know what's happening  
> I disabled tpm, then it went through...

Some clues from that chat. Unknown if actually relevant here.

**Comment by samueldr** [comment]
> [03:53] samueldr
> another thing to consider is that grub uses modules
>
> ```
> /boot/grub $ find /boot/grub/ -iname '*tpm*'
> /boot/grub/x86_64-efi/tpm.mod
> ```
> 
> no tpm here: https://github.com/NixOS/nixpkgs/blob/ced197be72099edcfa68ebed8b87af7b04851f45/nixos/modules/installer/cd-dvd/iso-image.nix#L246-L255

**Comment by ElvishJerricco** [comment]
To summarize one of our findings, it appears that Grub seems to care about external display output *in some cases*. When @zhaofengli tried a few different ISOs and USB-C docks, the scenarios where Grub successfully proceeded to launch the kernel all included having an external display plugged in. Not clear why this isn't the case for @samueldr's permanent Grub installation; unless you've never booted it with Grub without an external display plugged in.

**Comment by m1cr0man** [comment]
Just to chime in with my own experience. I spent a couple days debugging why I couldn't boot from USB (without a dock) nor from SD card. I could get the grub menu to appear, but selecting any option caused it to drop back to the Deck's boot manager. Doing this 3 times gave me a TPM error. It was suggested that I try disable the TPM, which worked, but I continued to debug with it on to see if I could find a root cause.

I found that stock NixOS (22.11+) images were also not booting, but an older (21.03) image I had worked fine, along with some other distro's images. What I did notice with 21.03 vs 22.11 was that grub was rendered in text mode.

I [compared the diff](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/installer/cd-dvd/iso-image.nix#L171) of the grub config for 21.03 and 22.11, and after not finding anything of note I started removing things related to theming. This allowed me to successfully boot the Deck into NixOS and subsequently the jovian isoGnome derivation.

In the end I found that setting `isoImage.grubTheme = lib.mkForce null;` created an image that would successfully boot every time. I would consider adding this to the [install ISO configuration](https://github.com/Jovian-Experiments/Jovian-NixOS/blob/development/default.nix#L16) to help other users.

**Comment by TheOPtimal** [comment]
> In the end I found that setting `isoImage.grubTheme = lib.mkForce null;` created an image that would successfully boot every time. I would consider adding this to the [install ISO configuration](https://github.com/Jovian-Experiments/Jovian-NixOS/blob/development/default.nix?rgh-link-date=2023-01-29T18%3A17%3A03Z#L16) to help other users.

Well...

```log
error: cannot coerce null to a string

       at /nix/store/gm8c760jh9w22vybdj99g1ciz2npmj7c-source/nixos/modules/installer/cd-dvd/iso-image.nix:312:14:

          311|     hiddenentry 'GUI mode' --hotkey 'g' {
          312|       $(find ${config.isoImage.grubTheme} -iname '*.pf2' -printf "loadfont (\$root)/EFI/boot/grub-theme/%P\n")
             |              ^
          313|       set textmode=false
(use '--show-trace' to show detailed location information)
```

**Comment by ElvishJerricco** [comment]
I was able to get a text mode boot with `isoImage.grubTheme = pkgs.runCommand "empty-dir" {} "mkdir $out";` EDIT: Scratch that. It boots *sometimes*.

**Comment by m1cr0man** [comment]
> I was able to get a text mode boot with `isoImage.grubTheme = pkgs.runCommand "empty-dir" {} "mkdir $out";` EDIT: Scratch that. It boots _sometimes_.

Fantastic idea! I didn't think to give it an empty folder.

As for the continued intermittent results, truthfully once it worked for me a couple times I went ahead and installed Jovian and stopped my investigation. Beforehand, I had 0 successful boots so this was a marked improvement.

**Comment by samueldr** [comment]
[new information from the matrix room from earlier today]

Apparently it is an issue for some other distros too. I haven't personally validated that information.

**Comment by ghost** [comment]
so this is still happening but disabling the grub theme still works

**Comment by ToyVo** [comment]
I just want to add another report of attaching a display allowed my built iso to boot.
In fact the official nixos installation iso also failed in the same way as the jovian iso I built, and attaching a display allowed the official nixos iso to boot as well. I had an archlinux iso on my ventoy usb and that booted just fine, the difference I notice between the two is that the nixos iso images use grub while the arch image and the nixos installation after connecting a display use systemd-boot, perhaps that is an area to investigate?

**Comment by samueldr** [comment]
With all the various ways it can be worked around, it smells like some form of issue made worse (better?) with timing, or race conditions. Though that's just a hunch...

**Comment by samueldr** [comment]
This is being fixed upstream, by me.

So remind me if in like 2-3 months, when the fix is already in Nixpkgs, and I forgot to come and close this.

PR:

 - https://github.com/NixOS/nixpkgs/pull/249218
