### ISSUE TITLE
Switching upstream from Valve to Bazzite might be interesting 

### ISSUE THREAD

**Issue by ahydronous** [Jovian-Experiments/Jovian-NixOS#445]
Bazzite is basically Valve's branch, but with a whole slew of fixes and extras applied, including a bunch of performance-related things.

I'm not sure if it will actually matter, but because Bazzite is based on Silverblue (immutable Fedora distro), there might be some assumptions in there that nicely transfer over to Jovian.

**Comment by K900** [comment]
Do you have specific changes that you'd say are important?

**Comment by ahydronous** [comment]
Euh, they are too numerous to name.

Take a peek at the About page: https://github.com/ublue-os/bazzite?tab=readme-ov-file#about--features
Or commit history: https://github.com/ublue-os/bazzite/commits/main/

As you can see its basically SteamOS++. I switched because there'd be annoying problems in SteamOS proper, the fix would be in the beta/master channel of SteamOS for months, but running that meant dealing with the instability of all the _other_ beta stuff. Bazzite would pull just the specific fixes forward, and sometimes even a fix for an adjacent problem caused by the fix.

**Comment by K900** [comment]
Then I'm sorry, but this is impractical. If you have specific suggestions other than "rebase on this completely incompatible project", we're open to those, but "just copy what those other people do" isn't it.

**Comment by samueldr** [comment]
I'm sorry, but if there are precise improvements you believe we are missing, feel free to request the features.

Otherwise, the list under *About & Features* is so generalistic that it's more of a NixOS configuration and personal system configuration topic than system integration for the Steam Deck client on a non-SteamOS. And a lot of others seem more like personal *preferences* or cargo culting than best practices.

Feel free to look at [our options page](https://jovian-experiments.github.io/Jovian-NixOS/options.html) and [our commit history](https://github.com/Jovian-Experiments/Jovian-NixOS/commits/development/) to see what features we have.

We do not intend to configure the non-steam area of the system otherwisely. It is left to the user's own preferences.

And finally, we're not even fully two contributors spending time on this project. We do not have the time or resources to “enhance” the experience on top of making this rock-solid foundation. The reason we're able to do so much with so little time and resources comes from the affordances from the NixOS options and the NixOS modules system. The same you are free to use to configure your system for the additional features.

**Comment by ahydronous** [comment]
I wasn't saying this needed to happen, stat.

My thinking was moreso that many of these patches are beneficial. There aren't particular one's that I'd cherrypick, but the holistic whole is a huge improvement over SteamOS proper. And even _if_ I could focus on which ones are beneficial, there'd be many more to follow and it'd be a neverending stream.

My idea was to take the current Bazzite, you then change it to a NixOS base/structure so that it is like Jovian is now, and that way it would be much easier to keep pulling in the patches in.

My bad if it came off the wrong way!
